In [1]:
import numpy as np

In [2]:
from pylab import *
from pprint import pprint


def arrayToList(arr):
    if type(arr) == type(array([])):
        return arrayToList(arr.tolist())
    elif type(arr) == type([]):
        return [arrayToList(a) for a in arr]
    else:
        return arr


def prettyArray(arr):
    pprint(arrayToList(arr))

In [6]:
AA = np.random.randint(0, 100, (12, 3))
print(AA)@

[[85  3 66]
 [49 94 52]
 [47 91 40]
 [21 36 48]
 [72  1 35]
 [55 16 58]
 [15 23 86]
 [60 84 22]
 [52 95 70]
 [99 62 90]
 [20 96 22]
 [99 67 74]]


In [7]:
prettyArray(AA)

[[85, 3, 66],
 [49, 94, 52],
 [47, 91, 40],
 [21, 36, 48],
 [72, 1, 35],
 [55, 16, 58],
 [15, 23, 86],
 [60, 84, 22],
 [52, 95, 70],
 [99, 62, 90],
 [20, 96, 22],
 [99, 67, 74]]
