# 📘 Contrôle NumPy 2025 — ET3 

Renommez ce fichier en : `ET3_MTX_2025_Nom_Prenom.ipynb`

### 1. Pourquoi NumPy ?
Expliquez en 3 phrases maximum pourquoi NumPy est souvent préféré aux listes Python classiques dans des calculs numériques. Donnez un exemple avec un calcul de sinus sur un tableau de données.

In [ ]:
# Votre réponse ici


### 2. Vitesse et vectorisation
1. Créez une liste `L` contenant les 100000 entiers de 0 à 99999. Mesurez le temps nécessaire pour créer une nouvelle liste `L2` contenant le carré de chaque élément de `L` (avec une boucle `for`).
2. Reproduisez l’opération avec un tableau NumPy `A` et comparez les temps d'exécution.

In [ ]:
# Votre code ici


### 3. Manipulations de vecteurs
1. Créez un tableau de 30 nombres entiers aléatoires entre 1 et 100.
2. Remplacez les valeurs supérieures à 80 par 80, et celles inférieures à 10 par 10.
3. Affichez la moyenne, le minimum et le maximum de ce tableau.

In [ ]:
# Votre code ici


### 4. Création de matrices
Créez une matrice 4×5 contenant les entiers de 1 à 20, organisés de manière à ce que chaque ligne contienne des nombres croissants par colonnes, mais des écarts différents par ligne :
```
[[  1   2   3   4   5]
 [ 10  12  14  16  18]
 [ 21  24  27  30  33]
 [ 40  44  48  52  56]]
```
Faites-le en une seule instruction NumPy si possible.

In [ ]:
# Votre code ici


### 5. Extraction conditionnelle
À partir d’une matrice `M` contenant les entiers de 0 à 99 (disposés en 10×10), extrayez :
- Les éléments pairs,
- Les multiples de 7,
- Les éléments strictement supérieurs à 60 et inférieurs à 75.

In [ ]:
# Votre code ici


### 6. Visualisation simple
Créez un tableau NumPy représentant un signal sinusoïdal bruité :
1. Générez 1000 points entre 0 et \(4\pi\),
2. Calculez le sinus de ces points, ajoutez un bruit gaussien `np.random.normal(0, 0.1, taille)`,
3. Affichez le tout avec `matplotlib.pyplot.plot` : en bleu le signal bruité, en rouge le signal pur.

In [ ]:
# Votre code ici
import numpy as np
import matplotlib.pyplot as plt

### 7. Initialisation et indexation
Créez un tableau T contenant les 25 premiers carrés parfaits (0² à 24²).
Affichez :
1. Les 5 premiers éléments,
2. Les 5 derniers,
3. Les éléments d’indice pair.

In [ ]:
# votre code ici 


### 8. Tableau 2D et remplacement conditionnel
Créez une matrice 6×6 d'entiers aléatoires entre 10 et 99. Modifiez-la selon les règles suivantes :
1. Remplacez tous les nombres pairs par leur moitié,
2. Remplacez tous les multiples de 5 par -5,
3. Affichez la matrice obtenue.

In [ ]:
# votre code ici


### 9. Filtrage avancé
Créez un tableau 1D de 100 éléments aléatoires entre 0 et 100. Affichez :
1. Les indices des éléments supérieurs à 80,
2. Les valeurs correspondantes,
3. Le nombre de ces valeurs.

In [ ]:
# votre code ici 


### 10. Création contrôlée de motifs
Créez une matrice 5×5 suivant ce motif :

```
[[ 1  2  3  4  5]
 [ 5  4  3  2  1]
 [ 1  2  3  4  5]
 [ 5  4  3  2  1]
 [ 1  2  3  4  5]]
 ````
Sans entrer les valeurs à la main : utilisez ```np.tile``` ou  ```np.vstack``` ou un empilement judicieux.


In [ ]:
# entrez votre code ici

### Exercice 11 — Lecture de données numériques
Objectif : lire un fichier texte contenant des valeurs numériques (ex : mesures expérimentales) et en extraire des informations statistiques.
Énoncé :
Un fichier texte donnees.txt contient une colonne de nombres flottants (une valeur par ligne), correspondant à des mesures physiques.
1. Chargez les données avec ```np.loadtxt("donnees.txt")```.
2. Calculez et affichez :
- la moyenne,
- l’écart-type,
- les valeurs supérieures à la moyenne.

In [ ]:
# entrez votre code ici

### Exercice 12 – Filtrage direct d’un tableau
Générez un tableau A de 100 entiers aléatoires entre 0 et 9.
1. Affichez tous les éléments de A strictement inférieurs à 3, en utilisant un filtre : A[A < 3].
2. Comptez combien il y en a.
3. Affichez leur position (indice) dans le tableau.

In [ ]:
# entrer votre code ici

### Exercice 13 – Utilisation de np.where pour transformer
Créez un tableau B de 50 réels uniformément répartis entre -5 et 5. Créez un tableau C tel que :
- Si la valeur de B est > 0, mettre 1,
- Sinon mettre 0.
Utilisez ```np.where```.

In [ ]:
# entrer votre code ici

### Exercice 14 – Substitution conditionnelle
Créez un tableau D de 20 entiers entre 0 et 20.
1. Remplacez tous les multiples de 3 par -3, les autres par D inchangé.
2. Puis, remplacez dans ce tableau tous les éléments > 15 par 100.

In [ ]:
# entrez votre code ici

### Exercice 15 – Conversion d’un tableau en matrice
Créez un tableau 1D de 36 entiers aléatoires entre 0 et 100.
1. Transformez-le en matrice 6×6.
2. Affichez la diagonale principale.

In [ ]:
# entrez votre code ici